# -*- coding: utf-8 -*-
"""protype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8xFd_VN-b7UmPEGevGDVWtWAiIe5KWP
"""

#pip install mne

# -*- coding: utf-8 -*-
"""
VMoGE v6 — Definitive Pipeline (1-Fold Prototype → 5-Fold Ready)
==================================================================
EEG-Based Alzheimer's Detection | Amsterdam UMC Masters Thesis

TO SWITCH 1 FOLD → 5 FOLDS:  NUM_FOLDS = 1  →  NUM_FOLDS = 5

ROOT CAUSES OF FD=91 / FN=63% — ALL FIXED HERE
-------------------------------------------------
The broken versions had drifted far from the reference that worked.
This file is a clean rebuild on that reference base.

[FIX 1] SFREQ was 128 Hz — data is recorded at 500 Hz.
        With SFREQ=128 the FREQ_MASK gave 309 clinical bins instead of 80,
        so every downstream shape was wrong and the encoder learned nothing.
        Fixed: SFREQ=500, N_SAMPLES=1000  (2-second epochs at 500 Hz).

[FIX 2] Encoder was replaced with simple nn.Linear experts — no Conv1d,
        no 3-layer GCN, no residual connections.
        The original SpectralFreqExpert + ThreeLayerGCN is what made the
        latent space meaningful in the working reference.
        Fixed: restored the original VMoGE_Encoder with kernels [32,16,8,4]
        and proper 3-layer GCN with residual connections.

[FIX 3] Warm-up trained on AD epochs only. With ~450 AD samples the encoder
        never saw HC patterns and produced an uninformative latent space.
        Fixed: warm-up trains on ALL training subjects (HC + AD) with
        WeightedRandomSampler, exactly as the working reference did.

[FIX 4] Generation used full DDPM reverse (T=200 slow loop) with no latent
        distribution fitting. The working reference used DDIM (50 steps) and
        sampled z from the fitted AD latent distribution using per-dimension
        sigma (LATENT_NOISE * sigma_ad) — keeping z near the real AD manifold.
        Fixed: restored DDIM + sigma_ad z-sampling.

[FIX 5] EEGNet took spectral input — the validated EEGNet operates on raw
        time-domain EEG (N,1,19,1000) with kernel (1,64). Restored.

[FIX 6] LAMBDA_REC was 0.5 — reference used 0.2. Restored.

IMPROVEMENTS KEPT FROM RECENT WORK (do not revert these)
----------------------------------------------------------
[+] Class-weighted cross-entropy in EEGNet (handles 29:15 HC:AD imbalance)
[+] DDPM_T=1000 with cosine schedule (reference value — not 200)
[+] FD with 5 bands + regularisation=1e-4 (more stable than 4 bands)
[+] PSD per-band comparison logged after generation
[+] FN profiling: theta/alpha and delta power of misclassified AD epochs
[+] Training loss printed every 20/50 epochs so you can monitor progress
[+] Results saved after every fold (never lose progress)
[+] Loss curve plots per fold
"""

# =============================================================================
# CELL 1 — IMPORTS
# =============================================================================
# %%
import os, sys, json, logging, math
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy import stats
from scipy.linalg import sqrtm

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, WeightedRandomSampler

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (accuracy_score, roc_auc_score, f1_score,
                              confusion_matrix)

# =============================================================================
# CELL 2 — CONFIGURATION 
# =============================================================================
import os
import sys
import torch

IS_COLAB = False  # Keep False for Hinton Cluster Execution

if IS_COLAB:
    from google.colab import drive
    if not os.path.exists('/content/drive'):
        drive.mount('/content/drive')
    SAVE_DIR    = '/content/drive/MyDrive/thesisproject/processed'
    RESULTS_DIR = '/content/drive/MyDrive/thesisproject/colab_results'
    NUM_FOLDS   = 5
    AUG_MULTIPLIER = 3
else:
    # ── TARGET THE PROCESSED DIRECTORy ──
    SAVE_DIR    = '/scratch/delmiari/thesisproject/processed'
    RESULTS_DIR = '/scratch/delmiari/thesisproject/pipeline_results'
    NUM_FOLDS   = 5         
    AUG_MULTIPLIER = 3       

os.makedirs(RESULTS_DIR, exist_ok=True)

# Hardware Resource Offloading 
DEVICE      = torch.device("cuda" if torch.cuda.is_available() else "cpu")
PIN_MEMORY  = (DEVICE.type == "cuda")
NUM_WORKERS = 8 if DEVICE.type == "cuda" else 0

print(f"=== HINTON ENVIRONMENT CHECK ===")
print(f"Active Script Directory : {os.path.dirname(os.path.abspath(__file__))}")
print(f"Resolved Data Directory : {SAVE_DIR}")
print(f"Files Detected in Path  : {os.listdir(SAVE_DIR) if os.path.exists(SAVE_DIR) else 'DIRECTORY DOES NOT EXIST'}")
print(f"================================\n")

# ── Signal parameters ─────────────────────────────────────────────────────────
N_CHANNELS  = 19
N_SAMPLES   = 1000       # 2 seconds × 500 Hz
SFREQ       = 500        # FIX [1]: was 128 in broken versions
N_RFFT      = N_SAMPLES // 2 + 1       # 501
ALL_FREQS   = np.fft.rfftfreq(N_SAMPLES, d=1.0 / SFREQ)
FREQ_MASK   = (ALL_FREQS >= 0.5) & (ALL_FREQS <= 40.0)
N_FREQ_CLIN = int(FREQ_MASK.sum())     # 80 bins  (correct only when SFREQ=500)

# ── Cross-validation ──────────────────────────────────────────────────────────
NUM_FOLDS    = 5         # 5 for full CV
RANDOM_STATE = 42

# ── EEGNet ────────────────────────────────────────────────────────────────────
EEGNET_EPOCHS   = 150
EEGNET_LR       = 1e-3
EEGNET_BATCH    = 32
EEGNET_PATIENCE = 10
EEGNET_DROPOUT  = 0.5

# ── VMoGE ─────────────────────────────────────────────────────────────────────
LATENT_DIM    = 128
DDPM_T        = 1000     
BETA_START    = 1e-4
BETA_END      = 0.02
WARMUP_EPOCHS = 80
JOINT_EPOCHS  = 250
VMOGE_LR      = 1e-4     
VMOGE_BATCH   = 16
LAMBDA_REC    = 0.2      

# ── Generation ────────────────────────────────────────────────────────────────
DDIM_STEPS     = 50      
LATENT_NOISE   = 0.15    
AUG_MULTIPLIER = 3    

# after generation, rescale each band's power in synthetic epochs to
# match the mean log band power of real AD training epochs.
# This is histogram/distribution matching applied to EEG spectral features.
# Reference: Reinhard et al. (2001) colour transfer, adapted to EEG bands.
APPLY_SPECTRAL_CORRECTION = True


# Down-weights easy HC examples (high p_t) and focuses on hard AD epochs.
# Directly targets the false negative problem observed in results.
# gamma=2 is the standard value from the paper.
USE_FOCAL_LOSS = True
FOCAL_GAMMA    = 2.0


AD_WEIGHT_MULTIPLIER = 3.0

# ── Quality gate ──────────────────────────────────────────────────────────────
FD_THRESHOLD = 5.0       

# ── Channel asymmetry indices ─────────────────────────────────────────────────
LEFT_CH  = [0, 2, 4, 6, 11, 13, 15]   # Fp1 F3 C3 F7 P3 P7 O1
RIGHT_CH = [1, 3, 5, 7, 12, 14, 16]   # Fp2 F4 C4 F8 P4 P8 O2

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
PIN_MEM = (DEVICE.type == 'cuda')

logging.basicConfig(level=logging.INFO, format='%(asctime)s | %(message)s',
                    handlers=[logging.StreamHandler(sys.stdout)])
log = logging.getLogger("VMoGE_v6")

print(f"Device: {DEVICE}")
print(f"SFREQ={SFREQ} Hz | N_SAMPLES={N_SAMPLES} | N_CLINICAL_BINS={N_FREQ_CLIN}")
print(f"NUM_FOLDS={NUM_FOLDS} | AUG×{AUG_MULTIPLIER} | LATENT_DIM={LATENT_DIM}")
assert N_FREQ_CLIN == 80, f"Expected 80 clinical bins, got {N_FREQ_CLIN}. Check SFREQ."

# =============================================================================
# CELL 3 — DIFFUSION SCHEDULE (linear, matches reference)
# =============================================================================
# %%
def make_schedule(device=DEVICE):
    betas = torch.linspace(BETA_START, BETA_END, DDPM_T).to(device)
    ab    = torch.cumprod(1 - betas, 0)
    return {'betas':    betas,
            'alpha_bars': ab,
            'sqrt_ab':    torch.sqrt(ab),
            'sqrt_1mab':  torch.sqrt(1 - ab)}

SCHEDULE = make_schedule()
print(f"DDPM schedule ready (T={DDPM_T})")

# =============================================================================
# CELL 4 — COMPLEX FFT REPRESENTATION  (reference implementation, unchanged)
# =============================================================================
HANNING = np.hanning(N_SAMPLES)

def signed_log(x):
    return np.sign(x) * np.log1p(np.abs(x))

def inv_signed_log(x):
    return np.sign(x) * np.expm1(np.abs(x))

def eeg_to_complex_spectrum(X):
    """
    (N, 19, 1000) → clin (N, 2, 19, 80), full (N, 2, 19, 501)
    Hanning window → rfft → signed-log transform.
    This is the exact function from the working reference.
    """
    N        = len(X)
    clin_out = np.zeros((N, 2, N_CHANNELS, N_FREQ_CLIN), dtype=np.float32)
    full_out = np.zeros((N, 2, N_CHANNELS, N_RFFT),      dtype=np.float32)
    for i, epoch in enumerate(X):
        fft_c           = np.fft.rfft(epoch * HANNING, axis=-1)
        real_sl         = signed_log(fft_c.real)
        imag_sl         = signed_log(fft_c.imag)
        full_out[i, 0]  = real_sl
        full_out[i, 1]  = imag_sl
        clin_out[i, 0]  = real_sl[:, FREQ_MASK]
        clin_out[i, 1]  = imag_sl[:, FREQ_MASK]
    return clin_out, full_out

def complex_spectrum_to_eeg(spec_full_norm, spec_mean, spec_std):
    """
    (N, 2, 19, 501) normalised → (N, 19, 1000) time-domain EEG.
    Exact irfft reconstruction — no phase pooling.
    """
    spec    = spec_full_norm * spec_std + spec_mean
    real_pt = inv_signed_log(spec[:, 0])
    imag_pt = inv_signed_log(spec[:, 1])
    eeg     = np.fft.irfft(real_pt + 1j * imag_pt, n=N_SAMPLES, axis=-1)
    for i in range(len(eeg)):
        s = eeg[i].std() + 1e-10
        eeg[i] = (eeg[i] - eeg[i].mean()) / s
    return eeg.astype(np.float32)

# =============================================================================
# CELL 5 — ADJACENCY MATRIX  
# =============================================================================

def build_adjacency(device=DEVICE):
    names = ['Fp1','Fp2','F7','F3','Fz','F4','F8',
             'T3','C3','Cz','C4','T4',
             'T5','P3','Pz','P4','T6','O1','O2']
    idx   = {n: i for i, n in enumerate(names)}
    n     = len(names)
    edges = [
        ('Fp1',['Fp2','F7','F3']),   ('Fp2',['Fp1','F8','F4']),
        ('F7', ['Fp1','F3','T3']),   ('F3', ['Fp1','F7','Fz','C3']),
        ('Fz', ['F3','F4','Cz']),    ('F4', ['Fp2','Fz','F8','C4']),
        ('F8', ['Fp2','F4','T4']),   ('T3', ['F7','C3','T5']),
        ('C3', ['F3','T3','Cz','P3']),('Cz',['Fz','C3','C4','Pz']),
        ('C4', ['F4','Cz','T4','P4']),('T4',['F8','C4','T6']),
        ('T5', ['T3','P3','O1']),    ('P3', ['C3','T5','Pz','O1']),
        ('Pz', ['Cz','P3','P4']),    ('P4', ['C4','Pz','T6','O2']),
        ('T6', ['T4','P4','O2']),    ('O1', ['T5','P3','Pz','O2']),
        ('O2', ['T6','P4','Pz','O1']),
    ]
    A = np.zeros((n, n))
    for ch, nbs in edges:
        for nb in nbs:
            A[idx[ch], idx[nb]] = A[idx[nb], idx[ch]] = 1.0
    At    = A + np.eye(n)
    D_inv = np.diag(1.0 / np.sqrt(At.sum(1) + 1e-10))
    return torch.FloatTensor(D_inv @ At @ D_inv).to(device)

ADJ = build_adjacency()

# =============================================================================
# CELL 6 — MODEL ARCHITECTURES  
# =============================================================================
# %%

# ── EEGNet (original — operates on raw time-domain EEG) ──────────────────────
# FIX [5]: restored to (N,1,19,1000) raw EEG input — Lawhern et al. 2018.
class EEGNet(nn.Module):
    def __init__(self, n_ch=N_CHANNELS, n_t=N_SAMPLES, dropout=EEGNET_DROPOUT):
        super().__init__()
        F1=8; D=2; F2=16
        self.block1 = nn.Sequential(
            nn.Conv2d(1, F1, (1, 64), padding=(0, 32), bias=False),
            nn.BatchNorm2d(F1),
            nn.Conv2d(F1, F1*D, (n_ch, 1), groups=F1, bias=False),
            nn.BatchNorm2d(F1*D), nn.ELU(),
            nn.AvgPool2d((1, 4)), nn.Dropout(dropout))
        self.block2 = nn.Sequential(
            nn.Conv2d(F1*D, F1*D, (1, 16), padding=(0, 8), groups=F1*D, bias=False),
            nn.Conv2d(F1*D, F2, (1, 1), bias=False),
            nn.BatchNorm2d(F2), nn.ELU(),
            nn.AvgPool2d((1, 8)), nn.Dropout(dropout))
        with torch.no_grad():
            self._flat = self.block2(
                self.block1(torch.zeros(1, 1, n_ch, n_t))).numel()
        self.fc = nn.Sequential(nn.Flatten(), nn.Linear(self._flat, 2))

    def forward(self, x):
        return self.fc(self.block2(self.block1(x)))


# ── VMoGE Encoder — restored from working reference ──────────────────────────

class GraphConvLayer(nn.Module):
    def __init__(self, in_f, out_f):
        super().__init__()
        self.W = nn.Linear(in_f, out_f, bias=True)
    def forward(self, H, A):
        return F.relu(self.W(torch.bmm(
            A.unsqueeze(0).expand(H.size(0), -1, -1), H)))


class ThreeLayerGCN(nn.Module):
    """
    3 GCN layers with residual connections.
    3 hops = reaches fronto-parietal connectivity (disrupted in AD).
    Residual connections prevent over-smoothing.
    Reference: Kipf & Welling (2017); Li et al. (2018)
    """
    def __init__(self, in_f, hidden=32, out_f=32):
        super().__init__()
        self.l1 = GraphConvLayer(in_f,   hidden)
        self.l2 = GraphConvLayer(hidden, hidden)
        self.l3 = GraphConvLayer(hidden, out_f)
        self.r1 = nn.Linear(in_f, hidden, bias=False) if in_f != hidden else nn.Identity()
        self.r3 = nn.Linear(hidden, out_f, bias=False) if hidden != out_f else nn.Identity()

    def forward(self, H, A):
        H1 = self.l1(H,  A) + self.r1(H)
        H2 = self.l2(H1, A) + H1
        H3 = self.l3(H2, A) + self.r3(H2)
        return H3


class SpectralFreqExpert(nn.Module):
    """
    Frequency-band expert: Conv1d over the 80 frequency bins,
    then 3-layer GCN over the 19 EEG channel nodes.
    kernels [32,16,8,4] → experts specialise broadband→narrowband.
    """
    def __init__(self, kernel, out_f=32):
        super().__init__()
        self.freq_conv = nn.Sequential(
            nn.Conv1d(2, 16, kernel_size=kernel, padding=kernel//2, bias=False),
            nn.BatchNorm1d(16), nn.ELU(),
            nn.AdaptiveAvgPool1d(16))      # → (B*19, 16, 16)
        self.gcn = ThreeLayerGCN(16 * 16, 32, out_f)

    def forward(self, spec, adj):
        B, C, Nch, Nf = spec.shape        # (B, 2, 19, 80)
        x = spec.permute(0, 2, 1, 3).reshape(B * Nch, C, Nf)  # (B*19, 2, 80)
        h = self.freq_conv(x)             # (B*19, 16, 16)
        h = h.view(B, Nch, -1)           # (B, 19, 256)
        return self.gcn(h, adj)           # (B, 19, out_f)


class GatingNetwork(nn.Module):
    def __init__(self, n_exp=4):
        super().__init__()
        self.net = nn.Sequential(
            nn.AdaptiveAvgPool2d(1), nn.Flatten(),
            nn.Linear(2, 16), nn.ReLU(),
            nn.Linear(16, n_exp), nn.Softmax(dim=-1))
    def forward(self, spec):
        return self.net(spec)


class VMoGE_Encoder(nn.Module):
    """
    VMoGE Encoder v5 — restored to working reference.
    Input:  (B, 2, 19, 80) — 2-channel clinical complex spectrum
    Output: z (B, 128)     — deterministic latent vector
    """
    KERNELS = [32, 16, 8, 4]

    def __init__(self, latent_dim=LATENT_DIM):
        super().__init__()
        self.experts = nn.ModuleList([SpectralFreqExpert(k) for k in self.KERNELS])
        self.gate    = GatingNetwork(4)
        self.fc_z    = nn.Sequential(
            nn.Linear(N_CHANNELS * 32, 256), nn.LayerNorm(256), nn.GELU(),
            nn.Dropout(0.1),
            nn.Linear(256, latent_dim), nn.Tanh())

    def forward(self, spec, adj):
        w    = self.gate(spec)
        outs = [e(spec, adj) for e in self.experts]
        comb = sum(w[:, i].view(-1, 1, 1) * outs[i] for i in range(4))
        return self.fc_z(comb.flatten(1))


# ── Reconstruction decoder (warm-up only) ────────────────────────────────────
class ComplexRecDecoder(nn.Module):
    def __init__(self, latent_dim=LATENT_DIM):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(latent_dim, 512), nn.LayerNorm(512), nn.GELU(),
            nn.Linear(512, 1024), nn.LayerNorm(1024), nn.GELU(),
            nn.Linear(1024, 2 * N_CHANNELS * N_FREQ_CLIN))
    def forward(self, z):
        return self.net(z).view(-1, 2, N_CHANNELS, N_FREQ_CLIN)


# ── Spectral diffusion decoder (2D UNet) ─────────────────────────────────────
class SinEmbed(nn.Module):
    def __init__(self, dim=128):
        super().__init__()
        self.dim = dim
    def forward(self, t):
        half  = self.dim // 2
        freqs = torch.exp(-np.log(10000) * torch.arange(half, device=t.device) / half)
        ang   = t.float().unsqueeze(1) * freqs.unsqueeze(0)
        return torch.cat([torch.sin(ang), torch.cos(ang)], 1)


class SpectralResBlock(nn.Module):
    def __init__(self, ch, t_dim=128, z_dim=LATENT_DIM):
        super().__init__()
        self.c1  = nn.Conv2d(ch, ch, 3, padding=1)
        self.c2  = nn.Conv2d(ch, ch, 3, padding=1)
        self.n1  = nn.GroupNorm(min(8, ch), ch)
        self.n2  = nn.GroupNorm(min(8, ch), ch)
        self.act = nn.SiLU()
        self.tp  = nn.Linear(t_dim, ch)
        self.zp  = nn.Linear(z_dim, ch)
    def forward(self, x, te, z):
        h = self.act(self.n1(self.c1(x)))
        h = h + self.tp(te).unsqueeze(-1).unsqueeze(-1)
        h = h + self.zp(z).unsqueeze(-1).unsqueeze(-1)
        return x + self.act(self.n2(self.c2(h)))


class SpectralDiffDecoder(nn.Module):
    """
    2D UNet DDPM decoder.
    Input:  (B, 2, 19, 501) noisy full spectrum + timestep t + z
    Output: (B, 2, 19, 501) predicted noise
    """
    def __init__(self, in_ch=2, t_dim=128, z_dim=LATENT_DIM):
        super().__init__()
        self.te  = SinEmbed(t_dim)
        self.tmp = nn.Sequential(nn.Linear(t_dim, t_dim*2), nn.SiLU(),
                                  nn.Linear(t_dim*2, t_dim))
        self.inc = nn.Conv2d(in_ch, 32, 3, padding=1)
        self.e1  = SpectralResBlock(32)
        self.d1  = nn.Conv2d(32, 64, (1, 4), stride=(1, 2), padding=(0, 1))
        self.e2  = SpectralResBlock(64)
        self.d2  = nn.Conv2d(64, 128, (1, 4), stride=(1, 2), padding=(0, 1))
        self.mid = SpectralResBlock(128)
        self.u2  = nn.ConvTranspose2d(128, 64, (1, 4), stride=(1, 2), padding=(0, 1))
        self.de2 = SpectralResBlock(128)
        self.u1  = nn.ConvTranspose2d(128, 32, (1, 4), stride=(1, 2), padding=(0, 1))
        self.de1 = SpectralResBlock(64)
        self.out = nn.Sequential(nn.GroupNorm(8, 64), nn.SiLU(), nn.Conv2d(64, in_ch, 1))

    def forward(self, x, t, z):
        te = self.tmp(self.te(t))
        x  = self.inc(x)
        e1 = self.e1(x,  te, z); x = self.d1(e1)
        e2 = self.e2(x,  te, z); x = self.d2(e2)
        x  = self.mid(x, te, z)
        x  = self.u2(x)
        h, w = min(x.shape[2], e2.shape[2]), min(x.shape[3], e2.shape[3])
        x  = self.de2(torch.cat([x[:,:,:h,:w], e2[:,:,:h,:w]], 1), te, z)
        x  = self.u1(x)
        h, w = min(x.shape[2], e1.shape[2]), min(x.shape[3], e1.shape[3])
        x  = self.de1(torch.cat([x[:,:,:h,:w], e1[:,:,:h,:w]], 1), te, z)
        x  = F.interpolate(x, size=(N_CHANNELS, N_RFFT), mode='bilinear', align_corners=False)
        return self.out(x)

# =============================================================================
# CELL 7 — TRAINING UTILITIES
# =============================================================================
# %%

def add_noise_4d(x0, t, sch):
    noise = torch.randn_like(x0)
    sab   = sch['sqrt_ab'][t].view(-1, 1, 1, 1)
    s1m   = sch['sqrt_1mab'][t].view(-1, 1, 1, 1)
    return sab * x0 + s1m * noise, noise


def make_weighted_loader(X, y, batch_size, shuffle=True):
    """DataLoader with class-balanced WeightedRandomSampler."""
    Xt = torch.FloatTensor(X).unsqueeze(1)   # (N, 1, 19, 1000)
    yt = torch.LongTensor(y)
    if shuffle:
        w       = 1.0 / np.bincount(y)[y]
        sampler = WeightedRandomSampler(torch.FloatTensor(w), len(w), True)
        return DataLoader(TensorDataset(Xt, yt), batch_size=batch_size, sampler=sampler)
    return DataLoader(TensorDataset(Xt, yt), batch_size=batch_size, shuffle=False)


def compute_metrics(y_true, y_pred, y_prob):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0,1]).ravel()
    return {
        'auc':         float(roc_auc_score(y_true, y_prob) * 100),
        'sensitivity': float(tp / (tp + fn + 1e-10) * 100),
        'specificity': float(tn / (tn + fp + 1e-10) * 100),
        'f1_macro':    float(f1_score(y_true, y_pred, average='macro') * 100),
        'tp': int(tp), 'tn': int(tn), 'fp': int(fp), 'fn': int(fn),
    }


@torch.no_grad()
def predict(model, X_np):
    model.eval()
    Xt     = torch.FloatTensor(X_np).unsqueeze(1)
    loader = DataLoader(TensorDataset(Xt), EEGNET_BATCH, shuffle=False)
    probs, preds = [], []
    for (xb,) in loader:
        logits = model(xb.to(DEVICE))
        probs.extend(torch.softmax(logits, 1)[:, 1].cpu().numpy())
        preds.extend(logits.argmax(1).cpu().numpy())
    return np.array(preds), np.array(probs)

# =============================================================================
# CELL 8 — SPECTRAL BIAS CORRECTION
# =============================================================================

def spectral_bias_correction(X_synth, X_real_ad):
    """
    Rescale synthetic EEG so its per-band log power matches the real AD
    training distribution.

    This is a soft spectral matching — it corrects the overall level of
    each band without destroying the inter-epoch variability.

    Parameters
    ----------
    X_synth   : (N_synth, 19, 1000) synthetic EEG
    X_real_ad : (N_ad,    19, 1000) real AD training EEG

    Returns
    -------
    X_corrected : (N_synth, 19, 1000) spectrally corrected synthetic EEG
    correction_log : dict of per-band correction factors applied
    """
    freqs = np.fft.rfftfreq(N_SAMPLES, d=1.0 / SFREQ)
    BANDS_CORR = {
        'delta': (0.5,  4.0),
        'theta': (4.0,  8.0),
        'alpha': (8.0, 13.0),
        'beta':  (13.0,30.0),
        'gamma': (30.0,40.0),
    }

    def mean_log_band_power(X, lo, hi, n_max=300):
        mask = (freqs >= lo) & (freqs < hi)
        vals = []
        for ep in X[:n_max]:
            psd = np.abs(np.fft.rfft(ep, axis=-1)) ** 2   # (19, 501)
            vals.append(np.log1p(psd[:, mask].mean()))
        return float(np.mean(vals))

    # Compute target (real) and current (synthetic) band power levels
    log.info("  Spectral bias correction:")
    band_corrections = {}
    for band, (lo, hi) in BANDS_CORR.items():
        p_real  = mean_log_band_power(X_real_ad, lo, hi)
        p_synth = mean_log_band_power(X_synth,   lo, hi)
        # Correction factor in linear power space
        correction = np.exp(p_real - p_synth)   # if synth too high, factor < 1
        band_corrections[band] = (lo, hi, float(correction))
        err_before = 100.0 * (p_synth - p_real) / (abs(p_real) + 1e-8)
        log.info(f"    {band:5s}: error={err_before:+.1f}%  correction_factor={correction:.4f}")

    # Apply correction in frequency domain
    X_corrected = np.zeros_like(X_synth)
    for i, epoch in enumerate(X_synth):
        fft_ep = np.fft.rfft(epoch, axis=-1)   # (19, 501) complex
        for band, (lo, hi, factor) in band_corrections.items():
            mask = (freqs >= lo) & (freqs < hi)
            fft_ep[:, mask] *= np.sqrt(factor)  # sqrt because power = |fft|^2
        corrected = np.fft.irfft(fft_ep, n=N_SAMPLES, axis=-1)
        # Re-normalise
        s = corrected.std() + 1e-10
        X_corrected[i] = (corrected - corrected.mean()) / s

    return X_corrected.astype(np.float32), band_corrections

# =============================================================================
# CELL 9 —  FOCAL LOSS
# Lin et al. (2017) ICCV
# =============================================================================

class FocalLoss(nn.Module):
    """
    Focal Loss: FL(p_t) = -(1 - p_t)^gamma * log(p_t)
    gamma=0 reduces to standard cross-entropy.
    gamma=2 (default) strongly down-weights easy examples.

    Combined with class weights to handle the 29:15 HC:AD imbalance.
    Reference: Lin et al. (2017) "Focal Loss for Dense Object Detection". ICCV.
    """
    def __init__(self, weight=None, gamma=FOCAL_GAMMA):
        super().__init__()
        self.weight = weight
        self.gamma  = gamma

    def forward(self, logits, targets):
        ce_loss = F.cross_entropy(logits, targets,
                                   weight=self.weight, reduction='none')
        pt      = torch.exp(-ce_loss)                    # probability of true class
        focal   = ((1.0 - pt) ** self.gamma) * ce_loss   # focal weight × CE
        return focal.mean()

# =============================================================================
# CELL 10 — TRAIN EEGNET  (with Focal Loss +  AD weight)
# =============================================================================


def train_eegnet(X_tr, y_tr, X_val, y_val, seed=42):
    """
    Train EEGNet with:
    - Focal Loss (Lin et al. 2017) 
    - Stronger AD class weight (AD_WEIGHT_MULTIPLIER=3) 
    - Early stopping on validation loss


    """
    torch.manual_seed(seed)
    model  = EEGNet().to(DEVICE)
    counts = np.bincount(y_tr)
    # Balanced weight then boosted by AD_WEIGHT_MULTIPLIER
    w_balanced = len(y_tr) / (len(counts) * counts)
    w_balanced[1] *= AD_WEIGHT_MULTIPLIER    # boost AD class weight
    cw = torch.FloatTensor(w_balanced).to(DEVICE)
    log.info(f"  EEGNet weights → HC:{cw[0]:.3f}  AD:{cw[1]:.3f}  "
             f"(focal={'on' if USE_FOCAL_LOSS else 'off'} γ={FOCAL_GAMMA})")

    criterion = FocalLoss(weight=cw, gamma=FOCAL_GAMMA) if USE_FOCAL_LOSS \
                else nn.CrossEntropyLoss(weight=cw)

    opt   = optim.Adam(model.parameters(), lr=EEGNET_LR, weight_decay=1e-4)
    sched = optim.lr_scheduler.CosineAnnealingLR(opt, EEGNET_EPOCHS, 1e-5)

    loader_tr  = make_weighted_loader(X_tr,  y_tr,  EEGNET_BATCH, shuffle=True)
    loader_val = make_weighted_loader(X_val, y_val, EEGNET_BATCH, shuffle=False)

    best_val, best_state, no_imp = float('inf'), None, 0

    for epoch in range(EEGNET_EPOCHS):
        model.train()
        for Xb, yb in loader_tr:
            Xb, yb = Xb.to(DEVICE), yb.to(DEVICE)
            opt.zero_grad()
            criterion(model(Xb), yb).backward()
            opt.step()
        sched.step()

        model.eval()
        vl = 0.0
        with torch.no_grad():
            for Xb, yb in loader_val:
                vl += F.cross_entropy(   # always use CE for val monitoring
                    model(Xb.to(DEVICE)), yb.to(DEVICE), weight=cw).item()
        vl /= len(loader_val)

        if vl < best_val - 1e-4:
            best_val, no_imp = vl, 0
            best_state = {k: v.clone() for k, v in model.state_dict().items()}
        else:
            no_imp += 1
            if no_imp >= EEGNET_PATIENCE:
                log.info(f"  EEGNet early stop at epoch {epoch+1}")
                break

    model.load_state_dict(best_state)
    return model

# =============================================================================
# CELL 11 — TRAIN VMoGE

# =============================================================================

def train_vmoge(X_ad_fold, X_all_fold, y_all_fold, seed=42):
    """
    Two-phase VMoGE training — restored to the working reference.

    Phase 1 (warm-up):
      Train encoder + rec_dec on ALL training subjects (HC + AD).


    Phase 2 (joint):
      Train encoder + diff_dec on AD epochs only.
      Diffusion decoder learns to generate AD spectra conditioned on z.

    Returns: encoder, diff_dec, full_mean, full_std, Z_ad, sigma_ad
    """
    torch.manual_seed(seed)

    log.info("    Computing spectral representations...")
    clin_all, full_all = eeg_to_complex_spectrum(X_all_fold)
    clin_ad,  full_ad  = eeg_to_complex_spectrum(X_ad_fold)

    # Normalise using this fold's training statistics only (no test leakage)
    clin_mean = clin_all.mean(); clin_std = clin_all.std() + 1e-10
    full_mean = full_all.mean(); full_std = full_all.std() + 1e-10

    clin_all_norm = (clin_all - clin_mean) / clin_std
    clin_ad_norm  = (clin_ad  - clin_mean) / clin_std
    full_ad_norm  = (full_ad  - full_mean) / full_std

    encoder  = VMoGE_Encoder().to(DEVICE)
    rec_dec  = ComplexRecDecoder().to(DEVICE)
    diff_dec = SpectralDiffDecoder().to(DEVICE)

    # ── Phase 1: Warm-up on ALL subjects ─────────────────────────────────────
    log.info(f"    Phase 1: Encoder warm-up ({WARMUP_EPOCHS} epochs, ALL subjects)...")
    w       = 1.0 / np.bincount(y_all_fold)[y_all_fold]
    sampler = WeightedRandomSampler(torch.FloatTensor(w), len(w), True)
    clin_t  = torch.FloatTensor(clin_all_norm)
    loader_w = DataLoader(TensorDataset(clin_t, clin_t),
                          VMOGE_BATCH, sampler=sampler, drop_last=True)

    opt_w = optim.AdamW(list(encoder.parameters()) + list(rec_dec.parameters()),
                         lr=VMOGE_LR, weight_decay=1e-4)
    sch_w = optim.lr_scheduler.CosineAnnealingLR(opt_w, WARMUP_EPOCHS, 1e-6)

    for epoch in range(WARMUP_EPOCHS):
        encoder.train(); rec_dec.train()
        for spec_b, tgt_b in loader_w:
            spec_b, tgt_b = spec_b.to(DEVICE), tgt_b.to(DEVICE)
            z    = encoder(spec_b, ADJ)
            loss = F.mse_loss(rec_dec(z), tgt_b)
            opt_w.zero_grad(); loss.backward()
            nn.utils.clip_grad_norm_(
                list(encoder.parameters()) + list(rec_dec.parameters()), 1.0)
            opt_w.step()
        sch_w.step()
        if (epoch + 1) % 20 == 0:
            log.info(f"      Warm-up {epoch+1}/{WARMUP_EPOCHS} | loss={loss.item():.5f}")

    # ── Phase 2: Joint training on AD only ───────────────────────────────────
    log.info(f"    Phase 2: Joint training ({JOINT_EPOCHS} epochs, AD only)...")
    loader_ad = DataLoader(
        TensorDataset(torch.FloatTensor(clin_ad_norm),
                      torch.FloatTensor(full_ad_norm)),
        VMOGE_BATCH, shuffle=True, drop_last=True)

    opt_j = optim.AdamW(list(encoder.parameters()) + list(diff_dec.parameters()),
                         lr=VMOGE_LR, weight_decay=1e-4)
    sch_j = optim.lr_scheduler.CosineAnnealingLR(opt_j, JOINT_EPOCHS, 1e-6)
    rec_dec.eval()

    for epoch in range(JOINT_EPOCHS):
        encoder.train(); diff_dec.train()
        for clin_b, full_b in loader_ad:
            clin_b, full_b = clin_b.to(DEVICE), full_b.to(DEVICE)
            z         = encoder(clin_b, ADJ)
            t_idx     = torch.randint(0, DDPM_T, (clin_b.size(0),), device=DEVICE)
            x_n, eps  = add_noise_4d(full_b, t_idx, SCHEDULE)
            loss_diff = F.mse_loss(diff_dec(x_n, t_idx, z), eps)
            with torch.no_grad():
                loss_rec = F.mse_loss(rec_dec(z.detach()), clin_b) * LAMBDA_REC
            loss = loss_diff + loss_rec
            opt_j.zero_grad(); loss.backward()
            nn.utils.clip_grad_norm_(
                list(encoder.parameters()) + list(diff_dec.parameters()), 1.0)
            opt_j.step()
        sch_j.step()
        if (epoch + 1) % 50 == 0:
            log.info(f"      Joint {epoch+1}/{JOINT_EPOCHS} | "
                     f"diff={loss_diff.item():.5f} | rec={loss_rec.item():.5f}")

    # ── Fit AD latent distribution (for z-sampling in generation) ────────────
    encoder.eval()
    all_z = []
    with torch.no_grad():
        for i in range(0, len(clin_ad_norm), 64):
            b = torch.FloatTensor(clin_ad_norm[i:i+64]).to(DEVICE)
            all_z.append(encoder(b, ADJ).cpu().numpy())
    Z_ad     = np.concatenate(all_z)        # (N_ad, 128) — real AD latent codes
    sigma_ad = Z_ad.std(0)                  # (128,) — per-dimension std

    log.info(f"    Z_ad shape: {Z_ad.shape} | sigma_ad mean: {sigma_ad.mean():.4f}")
    return encoder, diff_dec, full_mean, full_std, Z_ad, sigma_ad

# =============================================================================
# CELL 12 — GENERATE SYNTHETIC AD 
# =============================================================================

@torch.no_grad()
def generate_synthetic_ad(encoder, diff_dec, full_mean, full_std,
                            Z_ad, sigma_ad, n_samples):
    """
    Generate synthetic AD EEG using DDIM in full complex spectral space.
    This keeps z near the real AD manifold, preventing incoherent generation.
    Reference: Song et al. (2021) DDIM; Rombach et al. (2022) LDM.
    """
    encoder.eval(); diff_dec.eval()
    step_idx = torch.linspace(0, DDPM_T - 1, DDIM_STEPS + 1).long().flip(0)
    all_spec = []

    for i in range(0, n_samples, 50):
        n_this = min(50, n_samples - i)

        # Sample z: pick real AD codes + per-dimension perturbation
        idx    = np.random.randint(0, len(Z_ad), n_this)
        z_samp = Z_ad[idx] + LATENT_NOISE * sigma_ad * np.random.randn(n_this, LATENT_DIM)
        z_samp = np.clip(z_samp, -1.0, 1.0)
        z_t    = torch.FloatTensor(z_samp).to(DEVICE)

        x = torch.randn(n_this, 2, N_CHANNELS, N_RFFT, device=DEVICE)

        for j in range(DDIM_STEPS):
            t_now  = step_idx[j].to(DEVICE).expand(n_this)
            t_next = step_idx[j + 1]
            np_    = diff_dec(x, t_now, z_t)
            ab_now = SCHEDULE['alpha_bars'][step_idx[j]]
            ab_nxt = (SCHEDULE['alpha_bars'][t_next]
                      if t_next >= 0 else torch.tensor(1.0).to(DEVICE))
            x0p    = ((x - (1 - ab_now).sqrt() * np_) / ab_now.sqrt()).clamp(-4, 4)
            x      = ab_nxt.sqrt() * x0p + (1 - ab_nxt).sqrt() * np_

        all_spec.append(x.cpu().numpy())

    spec_norm = np.concatenate(all_spec)
    return complex_spectrum_to_eeg(spec_norm, full_mean, full_std)

# =============================================================================
# CELL 13 — EVALUATION METRICS
# =============================================================================

def compute_spectral_metrics(X_real_ad, X_synth):
    """Fréchet Distance + theta/alpha bias + Cohen's d."""
    freqs = np.fft.rfftfreq(N_SAMPLES, d=1.0 / SFREQ)
    BANDS = {'delta':(0.5,4),'theta':(4,8),'alpha':(8,13),'beta':(13,30),'gamma':(30,40)}

    def bp(X, lo, hi, n_max=200):
        mask = (freqs >= lo) & (freqs < hi)
        return np.array([
            np.mean([np.log1p((np.abs(np.fft.rfft(ep[ch]))**2)[mask].mean())
                     for ch in range(N_CHANNELS)])
            for ep in X[:n_max]])

    def tar(X, n_max=200):
        ratios = []
        for ep in X[:n_max]:
            r = []
            for ch in range(N_CHANNELS):
                psd   = np.abs(np.fft.rfft(ep[ch]))**2
                t_val = psd[(freqs >= 4) & (freqs < 8)].mean()
                a_val = psd[(freqs >= 8) & (freqs < 13)].mean()
                r.append(t_val / (a_val + 1e-10))
            ratios.append(np.mean(r))
        return np.array(ratios)

    def featurise(X, n_max=150):
        return np.array([
            [np.log1p(np.mean([np.log1p((np.abs(np.fft.rfft(ep[ch]))**2)
             [(freqs >= lo) & (freqs < hi)].mean())
             for ch in range(N_CHANNELS)])) for _, (lo, hi) in BANDS.items()]
            for ep in X[:n_max]], dtype=np.float32)

    def frechet(fr, fs):
        mr, ms = fr.mean(0), fs.mean(0)
        reg    = np.eye(fr.shape[1]) * 1e-4
        cr     = np.cov(fr, rowvar=False) + reg
        cs     = np.cov(fs, rowvar=False) + reg
        cm     = sqrtm(cr @ cs)
        if np.iscomplexobj(cm): cm = cm.real
        return max(float(np.real((mr-ms)@(mr-ms) + np.trace(cr+cs-2*cm))), 0.0)

    tar_r, tar_s   = tar(X_real_ad), tar(X_synth)
    feat_r, feat_s = featurise(X_real_ad), featurise(X_synth)
    fd             = frechet(feat_r, feat_s)

    log.info("  PSD comparison (real AD vs synthetic):")
    for band, (lo, hi) in BANDS.items():
        r = bp(X_real_ad, lo, hi).mean()
        s = bp(X_synth,   lo, hi).mean()
        err = 100.0 * (s - r) / (abs(r) + 1e-8)
        flag = "  ← HIGH" if abs(err) > 20 else ""
        log.info(f"    {band:5s}: real={r:.3f}  synth={s:.3f}  err={err:+.1f}%{flag}")

    return {
        'frechet':      fd,
        'tar_bias':     float(100.0*(tar_s.mean()-tar_r.mean())/(abs(tar_r.mean())+1e-8)),
        'ad_direction': bool(tar_s.mean() > tar_r.mean()),
    }


def evaluate_with_fn_profile(model, X_te, y_te):
    """Evaluate + profile False Negative epochs by theta/alpha and delta power."""
    y_pred, y_prob = predict(model, X_te)
    metrics = compute_metrics(y_te, y_pred, y_prob)

    if metrics['fn'] > 0:
        fn_idx = np.where((y_pred == 0) & (y_te == 1))[0]
        tp_idx = np.where((y_pred == 1) & (y_te == 1))[0]
        pct    = 100 * metrics['fn'] / max(metrics['fn'] + metrics['tp'], 1)
        log.warning(f"  [FN] {metrics['fn']} AD epochs misclassified as HC ({pct:.1f}%)")

        freqs = np.fft.rfftfreq(N_SAMPLES, d=1.0 / SFREQ)

        def band_power(idx_list, lo, hi):
            mask = (freqs >= lo) & (freqs < hi)
            vals = []
            for idx in idx_list[:100]:
                psd = np.abs(np.fft.rfft(X_te[idx], axis=-1)).mean(0) ** 2
                vals.append(np.log1p(psd[mask].mean()))
            return float(np.mean(vals)) if vals else float('nan')

        fn_theta = band_power(fn_idx, 4, 8);  fn_alpha = band_power(fn_idx, 8, 13)
        fn_delta = band_power(fn_idx, 0.5, 4); fn_ta   = fn_theta / (fn_alpha + 1e-8)
        log.info(f"   ├─ Missed AD:  delta={fn_delta:.3f}  theta={fn_theta:.3f}  "
                 f"alpha={fn_alpha:.3f}  θ/α={fn_ta:.3f}")

        if len(tp_idx) > 0:
            tp_theta = band_power(tp_idx, 4, 8); tp_alpha = band_power(tp_idx, 8, 13)
            tp_delta = band_power(tp_idx, 0.5, 4); tp_ta  = tp_theta / (tp_alpha + 1e-8)
            log.info(f"   ├─ Caught AD:  delta={tp_delta:.3f}  theta={tp_theta:.3f}  "
                     f"alpha={tp_alpha:.3f}  θ/α={tp_ta:.3f}")
            if fn_ta < tp_ta * 0.85:
                log.info("   └─ WHY: Missed AD has weaker theta/alpha slowing "
                         "(likely mild/early-stage or high individual variability)")
            elif fn_delta < tp_delta * 0.85:
                log.info("   └─ WHY: Missed AD has low delta power "
                         "(possible medication effect or atypical subtype)")
            else:
                log.info("   └─ WHY: No dominant spectral difference — failure may be "
                         "spatial/channel-level rather than global frequency content")

    return metrics, y_pred, y_prob

# =============================================================================
# CELL 14 — MAIN K-FOLD PIPELINE K-FOLD PIPELINE
# =============================================================================

def run_pipeline():
    # ─────────────────────────────────────────────────────────────────────────
    # DATA LOADING GENERATION — ACCORDING TO HINTON MATRIX SETUP
    # ─────────────────────────────────────────────────────────────────────────
    log.info(" Loading pre-saved numpy partitions from Google Drive upload...")
    
    def _load(fname):
        path = os.path.join(SAVE_DIR, fname)
        if not os.path.exists(path):
            avail = sorted(os.listdir(SAVE_DIR)) if os.path.isdir(SAVE_DIR) else []
            raise FileNotFoundError(f"Not found: {path}\nAvailable: {avail}")
        return np.load(path, allow_pickle=True)

    # ── Try-Except block (All 4 spaces inward) ──
    try:
        X_all   = np.concatenate([_load('X_train.npy'),            _load('X_test.npy')]).astype(np.float32)
        y_all   = np.concatenate([_load('y_train.npy'),            _load('y_test.npy')]).astype(np.int64)
        
        sub_raw = np.concatenate([_load('train_subject_ids.npy'),  _load('test_subject_ids.npy')])
        if sub_raw.dtype.kind in {'U', 'S'}:  
            sub_all = np.array([int(str(s).replace('sub-', '')) for s in sub_raw], dtype=np.int64)
        else:
            sub_all = sub_raw.astype(np.int64)
            
        log.info(f"✓ Data partitions compiled successfully!")
        log.info(f"  Total EEG Matrix Shape : {X_all.shape}")
        log.info(f"  Total Labels Matrix    : {y_all.shape}")
        log.info(f"  Total Subjects Tracked : {len(np.unique(sub_all))} unique individuals mapped")
        
    except FileNotFoundError as e:
        log.error(f" Data loading failed! Check files in {SAVE_DIR}")
        raise e

    # ─────────────────────────────────────────────────────────────────────────
    # POST-LOADING SANITY CHECKS & RE-ALIGNMENT
    # ─────────────────────────────────────────────────────────────────────────
    if X_all.shape[2] != N_SAMPLES:
        log.warning(f"Data has {X_all.shape[2]} time samples, config expects {N_SAMPLES}.")
        raise ValueError(f"Expected {N_SAMPLES} samples, got {X_all.shape[2]}")

    # Map the unique subjects using our clean integer variable
    unique_subs = np.unique(sub_all)
    sub_labels  = np.array([y_all[sub_all == s][0] for s in unique_subs])

    # Validate N_SAMPLES against loaded data
    if X_all.shape[2] != N_SAMPLES:
        log.warning(f"Data has {X_all.shape[2]} time samples, config expects {N_SAMPLES}.")
        log.warning("Update N_SAMPLES in the config cell to match your data.")

    # TO THIS UPDATED VERSION:
    unique_subs = np.unique(sub_all)
    sub_labels  = np.array([y_all[sub_all == s][0] for s in unique_subs])

    log.info(f"Data: {X_all.shape} | "
             f"HC={(y_all==0).sum()} | AD={(y_all==1).sum()} | "
             f"Subjects={len(unique_subs)}")

    # ── Cross-validation ──────────────────────────────────────────────────────
    n_splits    = max(2, NUM_FOLDS) if NUM_FOLDS < 5 else 5
    skf         = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=RANDOM_STATE)
    fold_results = []

    for fold_idx, (tv_idx, te_idx) in enumerate(skf.split(unique_subs, sub_labels)):
        if fold_idx >= NUM_FOLDS:
            break

        fold = fold_idx + 1
        log.info(f"\n{'='*70}")
        log.info(f"  FOLD {fold} / {NUM_FOLDS}")
        log.info(f"{'='*70}")

        tv_subs  = unique_subs[tv_idx]
        te_subs  = unique_subs[te_idx]

        # 80/20 inner split for EEGNet early stopping
        rng      = np.random.default_rng(fold_idx * 7 + RANDOM_STATE)
        perm     = rng.permutation(len(tv_subs))
        n_val    = max(2, int(len(tv_subs) * 0.20))
        val_subs = tv_subs[perm[:n_val]]
        tr_subs  = tv_subs[perm[n_val:]]

       
        def get(subs): mask = np.isin(sub_all, subs); return X_all[mask], y_all[mask]
        X_tr,  y_tr  = get(tr_subs)
        X_val, y_val = get(val_subs)
        X_te,  y_te  = get(te_subs)
        X_ad_tr      = X_tr[y_tr == 1]

        log.info(f"  Train: {len(X_tr)} ({(y_tr==0).sum()} HC, {(y_tr==1).sum()} AD) | "
                 f"Val: {len(X_val)} | Test: {len(X_te)}")

        # ── Stage 1a: Baseline EEGNet ─────────────────────────────────────────
        log.info("\n  [1a] Training baseline EEGNet (real data, class-weighted)...")
        model_bl = train_eegnet(X_tr, y_tr, X_val, y_val, seed=fold_idx*13+42)
        m_bl, _, _ = evaluate_with_fn_profile(model_bl, X_te, y_te)
        log.info(f"  Baseline → AUC={m_bl['auc']:.2f}%  Sens={m_bl['sensitivity']:.2f}%  "
                 f"Spec={m_bl['specificity']:.2f}%  F1={m_bl['f1_macro']:.2f}%")
        log.info(f"  CM → TP={m_bl['tp']} TN={m_bl['tn']} FP={m_bl['fp']} FN={m_bl['fn']}")

        # ── Stage 2a: Train VMoGE ─────────────────────────────────────────────
        log.info("\n  [2a] Training VMoGE (AD latent diffusion)...")
        (encoder, diff_dec,
         full_mean, full_std,
         Z_ad, sigma_ad) = train_vmoge(
            X_ad_fold  = X_ad_tr,
            X_all_fold = X_tr,
            y_all_fold = y_tr,
            seed       = fold_idx * 17 + 42)

        # ── Stage 3a: Quality gate ────────────────────────────────────────────
        log.info("\n  [3a] Quality gate — generating probe batch...")
        n_probe   = min(60, len(X_ad_tr))
        X_probe   = generate_synthetic_ad(encoder, diff_dec, full_mean, full_std,
                                           Z_ad, sigma_ad, n_probe)
        gen_q     = compute_spectral_metrics(X_ad_tr[:n_probe], X_probe)
        fd_val    = gen_q['frechet']
        log.info(f"  FD={fd_val:.4f}  (gate={FD_THRESHOLD})  "
                 f"θ/α bias={gen_q['tar_bias']:+.1f}%  "
                 f"AD direction={'✓' if gen_q['ad_direction'] else '✗'}")

        m_aug     = dict(m_bl)
        skip      = None

        if fd_val > FD_THRESHOLD or math.isnan(fd_val):
            skip = f"FD={fd_val:.3f} > {FD_THRESHOLD}"
            log.warning(f"  [GATE FAILED] {skip} — skipping augmentation")
        else:
            # ── Stage 3b: Generate synthetic AD ──────────────────────────────
            n_synth = min(len(X_ad_tr) * AUG_MULTIPLIER, 800)
            log.info(f"\n  [3b] Generating {n_synth} synthetic AD epochs (×{AUG_MULTIPLIER})...")
            X_synth = generate_synthetic_ad(encoder, diff_dec, full_mean, full_std,
                                             Z_ad, sigma_ad, n_synth)

            #  Spectral bias correction ─────────────────────
            if APPLY_SPECTRAL_CORRECTION:
                log.info("  [Spectral correction] Rescaling synthetic band power to match real AD...")
                X_synth, _ = spectral_bias_correction(X_synth, X_ad_tr)
                gen_q_post = compute_spectral_metrics(X_ad_tr[:100], X_synth[:100])
                log.info(f"  θ/α bias after correction: {gen_q_post['tar_bias']:+.1f}% "
                         f"(was {gen_q['tar_bias']:+.1f}% before)")

            # ── Stage 1b: Augmented EEGNet ────────────────────────────────────
            X_aug   = np.concatenate([X_tr, X_synth])
            y_aug   = np.concatenate([y_tr, np.ones(n_synth, dtype=np.int64)])
            log.info(f"\n  [1b] Training augmented EEGNet "
                     f"(HC={( y_aug==0).sum()}  AD={(y_aug==1).sum()})...")
            model_aug = train_eegnet(X_aug, y_aug, X_val, y_val, seed=fold_idx*23+42)
            m_aug, _, _ = evaluate_with_fn_profile(model_aug, X_te, y_te)
            log.info(f"  Augmented → AUC={m_aug['auc']:.2f}%  Sens={m_aug['sensitivity']:.2f}%  "
                     f"Spec={m_aug['specificity']:.2f}%  F1={m_aug['f1_macro']:.2f}%")
            log.info(f"  CM → TP={m_aug['tp']} TN={m_aug['tn']} FP={m_aug['fp']} FN={m_aug['fn']}")

        delta = m_aug['auc'] - m_bl['auc']
        log.info(f"\n  Fold {fold} ΔAUC = {delta:+.2f}pp  |  FD = {fd_val:.4f}")

        fold_result = {
            'fold': fold, 'fd': float(fd_val),
            'baseline': m_bl, 'augmented': m_aug,
            'generation': gen_q,
            'delta_auc': float(delta),
            'skip_reason': skip,
            'n_ad_train': int(len(X_ad_tr)),
            'n_synth': int(n_synth) if skip is None else 0,
        }
        fold_results.append(fold_result)

        out_path = os.path.join(RESULTS_DIR, 'fold_results.json')
        with open(out_path, 'w') as fp:
            json.dump(fold_results, fp, indent=2, default=str)
        log.info(f"  Saved → {out_path}")

        del encoder, diff_dec, model_bl
        if not skip: del model_aug
        if DEVICE.type == 'cuda': torch.cuda.empty_cache()

    # ── Summary ───────────────────────────────────────────────────────────────
    log.info(f"\n{'='*70}")
    log.info(f"  FINAL SUMMARY ({len(fold_results)} fold(s))")
    log.info(f"{'='*70}")
    for m in ['auc', 'sensitivity', 'specificity', 'f1_macro']:
        bl  = [r['baseline'][m]  for r in fold_results]
        aug = [r['augmented'][m] for r in fold_results]
        log.info(f"  {m.upper():12s} | BL={np.nanmean(bl):.2f}±{np.nanstd(bl):.2f}  "
                 f"| AUG={np.nanmean(aug):.2f}±{np.nanstd(aug):.2f}  "
                 f"| Δ={np.nanmean(aug)-np.nanmean(bl):+.2f}pp")

    return fold_results

# =============================================================================
# CELL 15 — RUN
# =============================================================================
# %%
if __name__ == '__main__':
    np.random.seed(RANDOM_STATE)
    torch.manual_seed(RANDOM_STATE)
    results = run_pipeline()
    log.info("Pipeline complete.")